### ISSUE TITLE
.sch files missing in pip package

### ISSUE THREAD

**Issue by cni-md** [niflows/nipype1-workflows#2]
I installed the pip package 0.0.1 and I want to use the  all_fmb_pipeline from
niflow.nipype1.workflows.dmri.fsl.artifacts.
This results in a error message hmc.sch not found.

Both .sch files are are not in the pip package at lib/python3.5/site-packages/niflow/nipype1/workflows/data/. I had to copy the files from github to solve this problem.

**Comment by effigies** [comment]
0.0.2 has been uploaded to PyPI.

Thanks for reporting this.
